from PyQt6.QtWidgets import QApplication, QMainWindow, QWidget, QVBoxLayout, QTableView
from PyQt6.QtGui import QStandardItemModel, QStandardItem
import sys
import psycopg2

# THIS FILE GENERATED BY CGPT TO DISPLAY DATA IN A SPREADSHEET IN PYQT6. IT WORKS.


def fetch_data():
    conn = psycopg2.connect(
        dbname="testdb", 
        user="postgres", 
        password="thirtean13", 
        host="localhost", 
        port="5432"
    )
    cursor = conn.cursor()
    cursor.execute("SELECT * FROM games;")
    rows = cursor.fetchall()
    colnames = [desc[0] for desc in cursor.description]
    cursor.close()
    conn.close()
    return colnames, rows



class MainWindow(QMainWindow):
    def __init__(self):
        super().__init__()
        self.setWindowTitle("Database Spreadsheet View")
        self.resize(800, 600)

        self.central_widget = QWidget()
        self.setCentralWidget(self.central_widget)
        layout = QVBoxLayout(self.central_widget)

        self.table_view = QTableView()
        layout.addWidget(self.table_view)

        self.load_data()

    def load_data(self):
        headers, data = fetch_data()

        model = QStandardItemModel()
        model.setColumnCount(len(headers))
        model.setHorizontalHeaderLabels(headers)

        for row_data in data:
            items = [QStandardItem(str(field)) for field in row_data]
            model.appendRow(items)

        self.table_view.setModel(model)

if __name__ == "__main__":
    app = QApplication(sys.argv)
    window = MainWindow()
    window.show()
    sys.exit(app.exec())
